# Generated by Django 6.0.3 on 2026-03-20 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='endurance_level',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Elite', 'Elite')], default='Medium', max_length=50),
        ),
        migrations.AddField(
            model_name='athlete',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in cm', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='injury_status',
            field=models.CharField(default='None', help_text="Current injury or 'None'", max_length=100),
        ),
        migrations.AddField(
            model_name='athlete',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(help_text='Coach Evaluation/Notes')),
                ('speed_trend', models.CharField(choices=[('Improving', 'Improving'), ('Stable', 'Stable'), ('Declining', 'Declining')], default='Stable', max_length=20)),
                ('strength_trend', models.CharField(choices=[('Improving', 'Improving'), ('Stable', 'Stable'), ('Declining', 'Declining')], default='Stable', max_length=20)),
                ('attendance_rate', models.IntegerField(default=100, help_text='Percentage 0-100')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='management.athlete')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Basket count', max_length=200)),
                ('target_value', models.CharField(help_text='e.g., 15pts', max_length=100)),
                ('current_value', models.CharField(help_text='e.g., 10pts', max_length=100)),
                ('status', models.CharField(choices=[('In Progress', 'In Progress'), ('Achieved', 'Achieved'), ('On Hold', 'On Hold')], default='In Progress', max_length=50)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='management.athlete')),
            ],
        ),
    ]
