# Generated by Django 6.0.3 on 2026-03-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_athlete_endurance_level_athlete_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='duration_minutes',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Missed', 'Missed')], default='Scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='notes',
            field=models.TextField(),
        ),
    ]
