# Generated by Django 6.0.3 on 2026-03-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_trainingsession_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='plain_password',
            field=models.CharField(blank=True, help_text='Plain text password (Admin access only)', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='plain_password',
            field=models.CharField(blank=True, help_text='Plain text password (Admin access only)', max_length=128, null=True),
        ),
    ]
