# Generated by Django 6.0.3 on 2026-03-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_athlete_plain_password_coach_plain_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='sports',
            field=models.TextField(blank=True, help_text='Comma-separated list of sports', null=True),
        ),
    ]
