# Generated by Django 6.0.3 on 2026-03-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_athlete_sports'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='sports',
            field=models.TextField(blank=True, help_text='Comma-separated list of sports', null=True),
        ),
    ]
