# Generated by Django 6.0.3 on 2026-03-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_coach_sports'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='sports',
            field=models.TextField(blank=True, help_text='Sport for this session', null=True),
        ),
    ]
