# Generated by Django 6.0.3 on 2026-03-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_trainingsession_sports'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='sports',
            field=models.TextField(blank=True, help_text='Sport for this payment', null=True),
        ),
    ]
