# Generated by Django 6.0.3 on 2026-04-02 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_announcement_attendance_message_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketballStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('rebounds', models.IntegerField(default=0)),
                ('speed', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('athlete', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='basketball_stats', to='management.athlete')),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='management.athlete')),
                ('coach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.coach')),
            ],
        ),
    ]
