# Generated by Django 6.0.3 on 2026-04-02 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_basketballstat_incident'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent', models.CharField(max_length=200)),
                ('venue', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('points', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('rebounds', models.IntegerField(default=0)),
                ('win', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_records', to='management.athlete')),
            ],
        ),
    ]
