# Generated by Django 6.0.3 on 2026-04-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_gamerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='grade_level',
            field=models.CharField(blank=True, default='Active', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='jersey_number',
            field=models.CharField(blank=True, default='#--', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='position',
            field=models.CharField(blank=True, default='Player', max_length=50, null=True),
        ),
    ]
