# Generated by Django 6.0.3 on 2026-04-03 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_athlete_grade_level_athlete_jersey_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='management.coach'),
        ),
    ]
