# Generated by Django 6.0.3 on 2026-04-04 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_trainingsession_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Over-the-counter', 'Over-the-counter'), ('GCash', 'GCash'), ('BDO', 'BDO'), ('Metrobank', 'Metrobank')], default='Over-the-counter', max_length=50),
        ),
    ]
