# Generated by Django 6.0.3 on 2026-04-04 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='career_milestones',
            field=models.TextField(blank=True, help_text='Semicolon-separated list of milestones', null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='experience_years',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coach',
            name='injury_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='push_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='coach',
            name='weekly_reports',
            field=models.BooleanField(default=True),
        ),
    ]
