
from django.urls import path
from . import views

app_name = 'management'

urlpatterns = [
    path('welcome/', views.coach_landing, name='landing'),
    path('coach/portal/', views.coach_portal_landing, name='coach_portal_landing'),
    path('admin/portal/', views.admin_portal_landing, name='admin_portal_landing'),
    path('coach/login/', views.coach_login, name='coach_login'),
    path('admin/login/', views.admin_login, name='admin_login'),
    path('admin/register-coach/', views.admin_register_coach, name='admin_register_coach'),
    path('admin/register-athlete/', views.admin_register_athlete, name='admin_register_athlete'),
    path('admin/coaches/', views.coach_list, name='coach_list'),
    path('admin/coach/<int:pk>/', views.coach_detail, name='coach_detail'),
    path('admin/coach/<int:pk>/edit/', views.coach_update, name='coach_update'),
    path('admin/coach/<int:pk>/delete/', views.coach_delete, name='coach_delete'),
    path('admin/athlete/<int:pk>/', views.athlete_detail, name='athlete_detail'),
    path('admin/notification/read/<int:pk>/', views.mark_notification_read, name='mark_notification_read'),
    path('admin/notifications/mark-all-read/', views.mark_all_notifications_read, name='mark_all_notifications_read'),
    path('monitor-progress/', views.monitor_progress, name='monitor_progress'),
    path('monitor-progress/add-evaluation/<int:athlete_id>/', views.add_evaluation, name='add_evaluation'),
    path('monitor-progress/add-goal/<int:athlete_id>/', views.add_goal, name='add_goal'),
    path('monitor-progress/update-goal/<int:goal_id>/', views.update_goal, name='update_goal'),
    path('monitor-progress/delete-goal/<int:goal_id>/', views.delete_goal, name='delete_goal'),
    path('monitor-progress/add-performance/<int:athlete_id>/', views.add_performance_record, name='add_performance_record'),
    path('', views.athlete_list, name='athlete_list'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('athlete-dashboard/', views.athlete_dashboard, name='athlete_dashboard'),
    path(
        'athlete-dashboard/my-progress-report/',
        views.athlete_my_progress_report,
        name='athlete_my_progress_report',
    ),
    path('athlete-registration/', views.register_athlete, name='register_athlete'),
    path('athlete-profile/update/', views.athlete_profile_update, name='athlete_profile_update'),
    path('report/', views.generate_report, name='generate_report'),
    path('create/', views.athlete_create, name='athlete_create'),
    path('update/<int:pk>/', views.athlete_update, name='athlete_update'),
    path('delete/<int:pk>/', views.athlete_delete, name='athlete_delete'),
    path('sessions/', views.training_session_list, name='training_session_list'),
    path('sessions/create/', views.training_session_create, name='training_session_create'),
    path('sessions/update/<int:pk>/', views.training_session_update, name='training_session_update'),
    path('sessions/delete/<int:pk>/', views.training_session_delete, name='training_session_delete'),
    path('payments/', views.payment_list, name='payment_list'),
    path('payments/create/', views.payment_create, name='payment_create'),
    path('payments/update/<int:pk>/', views.payment_update, name='payment_update'),
    path('payments/delete/<int:pk>/', views.payment_delete, name='payment_delete'),
    path('evaluation/create/', views.evaluation_create, name='evaluation_create'),
    path('announcement/create/', views.announcement_create, name='announcement_create'),
    path('performance/update-analytics/<int:athlete_id>/', views.update_performance_analytics, name='update_performance_analytics'),
    path('report/generate/', views.generate_report_pdf, name='generate_report'),

    # Basketball Coach Dashboard App endpoints
    path('api/update-basketball-stats/<int:athlete_id>/', views.update_basketball_stats, name='update_basketball_stats'),
    path('needs-attention/', views.needs_attention, name='needs_attention'),
    path('needs-attention/mark-attendance/', views.mark_attendance, name='mark_attendance'),
    path('message-athlete/', views.message_athlete, name='message_athlete'),
    path('basketball-analytics/', views.basketball_analytics, name='basketball_analytics'),
    path('log-incident/', views.log_incident, name='log_incident'),
    path('compare-athletes/', views.player_comparison, name='player_comparison'),
    path('update_coach_bio/', views.update_coach_bio, name='update_coach_bio'),
    path('update_coach_notifs/', views.update_coach_notifs, name='update_coach_notifs'),
    path('update_coach_photo/', views.update_coach_photo, name='update_coach_photo'),
    path('notification-history/', views.notification_history, name='notification_history'),
    path('api/mark-notifications-read/', views.mark_notifications_read, name='mark_notifications_read'),
]
